package calculos;

import RA.AerogeneradorRA;
import RA.AsuntoPosicionRA;
import RA.AsuntoRA;
import RA.DatosRA2;
import RA.NormaRA;
import RA.PosicionRA;
import com.vividsolutions.jts.geom.LineString;
import general.Auxiliares;
import general.ComboBoxObject;
import general.IVExtendido;
import general.MensajeApp;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class CalculoAnguloLibre extends javax.swing.JDialog {
    public CalculoAnguloLibre(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jpClave = new javax.swing.JPanel();
        jlAsunto = new javax.swing.JLabel();
        jcbAsunto = new javax.swing.JComboBox();
        jlNorma = new javax.swing.JLabel();
        jtfNorma = new javax.swing.JTextField();
        jlPosAero = new javax.swing.JLabel();
        jtfPosAero = new javax.swing.JTextField();
        jlPosBuje = new javax.swing.JLabel();
        jtfPosBuje = new javax.swing.JTextField();
        jlPosMicro1 = new javax.swing.JLabel();
        jtfPosMicro1 = new javax.swing.JTextField();
        jlPosMicro2 = new javax.swing.JLabel();
        jtfPosMicro2 = new javax.swing.JTextField();
        jlPosMicro3 = new javax.swing.JLabel();
        jtfPosMicro3 = new javax.swing.JTextField();
        jlPosMicro4 = new javax.swing.JLabel();
        jtfPosMicro4 = new javax.swing.JTextField();
        jlRutaMallado = new javax.swing.JLabel();
        jtfRutaMallado = new javax.swing.JTextField();
        jbSelRuta = new javax.swing.JButton();
        jbCalcular = new javax.swing.JButton();
        jpCalculos = new javax.swing.JPanel();
        jlAngMicro1Aero = new javax.swing.JLabel();
        jtfAngMicro1Aero = new javax.swing.JTextField();
        jlAngMicro1AeroSufijo = new javax.swing.JLabel();
        jlAngMicro2Aero = new javax.swing.JLabel();
        jtfAngMicro2Aero = new javax.swing.JTextField();
        jlAngMicro2AeroSufijo = new javax.swing.JLabel();
        jlAngMicro3Aero = new javax.swing.JLabel();
        jtfAngMicro3Aero = new javax.swing.JTextField();
        jlAngMicro3AeroSufijo = new javax.swing.JLabel();
        jlAngMicro4Aero = new javax.swing.JLabel();
        jtfAngMicro4Aero = new javax.swing.JTextField();
        jlAngMicro4AeroSufijo = new javax.swing.JLabel();
        jlfAngLibreMicro1Aero = new javax.swing.JLabel();
        jtfAngLibreMicro1Aero = new javax.swing.JTextField();
        jlfAngLibreMicro1AeroSufijo = new javax.swing.JLabel();
        jlfAngLibreMicro2Aero = new javax.swing.JLabel();
        jtfAngLibreMicro2Aero = new javax.swing.JTextField();
        jlfAngLibreMicro2AeroSufijo = new javax.swing.JLabel();
        jlfAngLibreMicro3Aero = new javax.swing.JLabel();
        jtfAngLibreMicro3Aero = new javax.swing.JTextField();
        jlfAngLibreMicro3AeroSufijo = new javax.swing.JLabel();
        jlfAngLibreMicro4Aero = new javax.swing.JLabel();
        jtfAngLibreMicro4Aero = new javax.swing.JTextField();
        jlfAngLibreMicro4AeroSufijo = new javax.swing.JLabel();
        jlResMicro1Aero = new javax.swing.JLabel();
        jlResMicro2Aero = new javax.swing.JLabel();
        jlResMicro3Aero = new javax.swing.JLabel();
        jlResMicro4Aero = new javax.swing.JLabel();
        jlPosLibre1 = new javax.swing.JLabel();
        jtfPosLibre1 = new javax.swing.JTextField();
        jlPosLibre2 = new javax.swing.JLabel();
        jtfPosLibre2 = new javax.swing.JTextField();
        jlPosLibre3 = new javax.swing.JLabel();
        jtfPosLibre3 = new javax.swing.JTextField();
        jlPosLibre4 = new javax.swing.JLabel();
        jtfPosLibre4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CÁLCULO DE ÁNGULOS DE RECTAS");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jpClave.setBackground(new java.awt.Color(255, 255, 255));
        jpClave.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jlAsunto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAsunto.setText("Asunto:");

        jcbAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioAsunto(evt);
            }
        });

        jlNorma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlNorma.setText("Norma de Aplicación:");

        jtfNorma.setEditable(false);
        jtfNorma.setBackground(new java.awt.Color(204, 204, 204));
        jtfNorma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNorma.setFocusable(false);

        jlPosAero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosAero.setText("Posición Aerogenerador:");

        jtfPosAero.setEditable(false);
        jtfPosAero.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosAero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosBuje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosBuje.setText("Posición Buje:");

        jtfPosBuje.setEditable(false);
        jtfPosBuje.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosBuje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosMicro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosMicro1.setText("Posición Micrófono 1:");

        jtfPosMicro1.setEditable(false);
        jtfPosMicro1.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosMicro1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosMicro2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosMicro2.setText("Posición Micrófono 2:");

        jtfPosMicro2.setEditable(false);
        jtfPosMicro2.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosMicro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosMicro3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosMicro3.setText("Posición Micrófono 3:");

        jtfPosMicro3.setEditable(false);
        jtfPosMicro3.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosMicro3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosMicro4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosMicro4.setText("Posición Micrófono 4:");

        jtfPosMicro4.setEditable(false);
        jtfPosMicro4.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosMicro4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlRutaMallado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlRutaMallado.setText("Ruta mallado:");

        jtfRutaMallado.setEnabled(false);
        jtfRutaMallado.setName("Ruta mallado"); // NOI18N

        jbSelRuta.setBackground(new java.awt.Color(255, 255, 255));
        jbSelRuta.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage("\\\\B2solar\\Datos\\Curva\\Imagenes\\OpenFolder.gif" )));
        jbSelRuta.setToolTipText("Seleccionar fichero de datos");
        jbSelRuta.setEnabled(false);
        jbSelRuta.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbSelRuta.setPreferredSize(new java.awt.Dimension(65, 20));
        jbSelRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarRuta(evt);
            }
        });

        javax.swing.GroupLayout jpClaveLayout = new javax.swing.GroupLayout(jpClave);
        jpClave.setLayout(jpClaveLayout);
        jpClaveLayout.setHorizontalGroup(
            jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClaveLayout.createSequentialGroup()
                        .addComponent(jlAsunto)
                        .addGap(18, 18, 18)
                        .addComponent(jcbAsunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpClaveLayout.createSequentialGroup()
                        .addComponent(jlNorma)
                        .addGap(25, 25, 25)
                        .addComponent(jtfNorma, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                    .addGroup(jpClaveLayout.createSequentialGroup()
                        .addComponent(jlPosAero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPosAero))
                    .addGroup(jpClaveLayout.createSequentialGroup()
                        .addComponent(jlPosBuje)
                        .addGap(65, 65, 65)
                        .addComponent(jtfPosBuje))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpClaveLayout.createSequentialGroup()
                        .addComponent(jlRutaMallado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRutaMallado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpClaveLayout.createSequentialGroup()
                        .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlPosMicro2)
                            .addComponent(jlPosMicro3)
                            .addComponent(jlPosMicro4)
                            .addComponent(jlPosMicro1))
                        .addGap(24, 24, 24)
                        .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPosMicro3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPosMicro2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfPosMicro1)
                            .addComponent(jtfPosMicro4))))
                .addContainerGap())
        );
        jpClaveLayout.setVerticalGroup(
            jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClaveLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAsunto)
                    .addComponent(jcbAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNorma)
                    .addComponent(jtfNorma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPosAero)
                    .addComponent(jtfPosAero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosBuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosBuje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosMicro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosMicro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPosMicro2)
                    .addComponent(jtfPosMicro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPosMicro3)
                    .addComponent(jtfPosMicro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPosMicro4)
                    .addComponent(jtfPosMicro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlRutaMallado)
                        .addComponent(jtfRutaMallado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbCalcular.setText("CALCULAR");
        jbCalcular.setEnabled(false);
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularAngulos(evt);
            }
        });

        jpCalculos.setBackground(new java.awt.Color(255, 255, 255));
        jpCalculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlAngMicro1Aero.setText("<html>φ<sub>Micro1-Aero</sub></html>");

        jtfAngMicro1Aero.setEditable(false);
        jtfAngMicro1Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngMicro1Aero.setName("Zref"); // NOI18N

        jlAngMicro1AeroSufijo.setText("º");

        jlAngMicro2Aero.setText("<html>φ<sub>Micro2-Aero</sub></html>");

        jtfAngMicro2Aero.setEditable(false);
        jtfAngMicro2Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngMicro2Aero.setName("Z0_ref"); // NOI18N

        jlAngMicro2AeroSufijo.setText("º");

        jlAngMicro3Aero.setText("<html>φ<sub>Micro3-Aero</sub></html>");

        jtfAngMicro3Aero.setEditable(false);
        jtfAngMicro3Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngMicro3Aero.setName("Z0"); // NOI18N

        jlAngMicro3AeroSufijo.setText("º");

        jlAngMicro4Aero.setText("<html>φ<sub>Micro4-Aero</sub></html>");

        jtfAngMicro4Aero.setEditable(false);
        jtfAngMicro4Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngMicro4Aero.setName("Z0"); // NOI18N

        jlAngMicro4AeroSufijo.setText("º");

        jlfAngLibreMicro1Aero.setText("<html>φ<sub>Min Libre Micro1-Aero</sub></html>");

        jtfAngLibreMicro1Aero.setEditable(false);
        jtfAngLibreMicro1Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngLibreMicro1Aero.setName("Zref"); // NOI18N

        jlfAngLibreMicro1AeroSufijo.setText("º");

        jlfAngLibreMicro2Aero.setText("<html>φ<sub>Min Libre Micro2-Aero</sub></html>");

        jtfAngLibreMicro2Aero.setEditable(false);
        jtfAngLibreMicro2Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngLibreMicro2Aero.setName("Z0_ref"); // NOI18N

        jlfAngLibreMicro2AeroSufijo.setText("º");

        jlfAngLibreMicro3Aero.setText("<html>φ<sub>Min Libre Micro3-Aero</sub></html>");

        jtfAngLibreMicro3Aero.setEditable(false);
        jtfAngLibreMicro3Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngLibreMicro3Aero.setName("Z0"); // NOI18N

        jlfAngLibreMicro3AeroSufijo.setText("º");

        jlfAngLibreMicro4Aero.setText("<html>φ<sub>Min Libre Micro4-Aero</sub></html>");

        jtfAngLibreMicro4Aero.setEditable(false);
        jtfAngLibreMicro4Aero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfAngLibreMicro4Aero.setName("Z0"); // NOI18N

        jlfAngLibreMicro4AeroSufijo.setText("º");

        jlResMicro1Aero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlResMicro1Aero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResMicro1Aero.setText("OK - NO OK");
        jlResMicro1Aero.setOpaque(true);

        jlResMicro2Aero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlResMicro2Aero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResMicro2Aero.setText("OK - NO OK");
        jlResMicro2Aero.setOpaque(true);

        jlResMicro3Aero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlResMicro3Aero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResMicro3Aero.setText("OK - NO OK");
        jlResMicro3Aero.setOpaque(true);

        jlResMicro4Aero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlResMicro4Aero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlResMicro4Aero.setText("OK - NO OK");
        jlResMicro4Aero.setOpaque(true);

        jlPosLibre1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosLibre1.setText("Posición Obst. 1:");

        jtfPosLibre1.setEditable(false);
        jtfPosLibre1.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosLibre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosLibre2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosLibre2.setText("Posición Obst. 2:");

        jtfPosLibre2.setEditable(false);
        jtfPosLibre2.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosLibre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosLibre3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosLibre3.setText("Posición Obst. 3:");

        jtfPosLibre3.setEditable(false);
        jtfPosLibre3.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosLibre3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlPosLibre4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlPosLibre4.setText("Posición Obst. 4:");

        jtfPosLibre4.setEditable(false);
        jtfPosLibre4.setBackground(new java.awt.Color(204, 204, 204));
        jtfPosLibre4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jpCalculosLayout = new javax.swing.GroupLayout(jpCalculos);
        jpCalculos.setLayout(jpCalculosLayout);
        jpCalculosLayout.setHorizontalGroup(
            jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalculosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCalculosLayout.createSequentialGroup()
                        .addComponent(jlAngMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAngMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlAngMicro1AeroSufijo)
                        .addGap(18, 18, 18)
                        .addComponent(jlfAngLibreMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAngLibreMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlfAngLibreMicro1AeroSufijo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlResMicro1Aero, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(jpCalculosLayout.createSequentialGroup()
                        .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlAngMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlAngMicro2AeroSufijo))
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlAngMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlAngMicro3AeroSufijo))
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlAngMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlAngMicro4AeroSufijo)))
                        .addGap(18, 18, 18)
                        .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlfAngLibreMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngLibreMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlfAngLibreMicro2AeroSufijo))
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlfAngLibreMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngLibreMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlfAngLibreMicro3AeroSufijo))
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlfAngLibreMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAngLibreMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlfAngLibreMicro4AeroSufijo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlResMicro2Aero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlResMicro3Aero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlResMicro4Aero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpCalculosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addComponent(jlPosLibre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPosLibre1))
                            .addGroup(jpCalculosLayout.createSequentialGroup()
                                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlPosLibre2)
                                        .addComponent(jlPosLibre3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jlPosLibre4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPosLibre4)
                                    .addComponent(jtfPosLibre3)
                                    .addComponent(jtfPosLibre2))))))
                .addContainerGap())
        );
        jpCalculosLayout.setVerticalGroup(
            jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalculosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAngMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAngMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAngMicro1AeroSufijo))
                    .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlfAngLibreMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAngLibreMicro1Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlfAngLibreMicro1AeroSufijo)
                        .addComponent(jlResMicro1Aero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosLibre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosLibre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAngMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAngMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAngMicro2AeroSufijo))
                    .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfAngLibreMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlfAngLibreMicro2AeroSufijo)
                        .addComponent(jlResMicro2Aero)
                        .addComponent(jlfAngLibreMicro2Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosLibre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosLibre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAngMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAngMicro3AeroSufijo)
                        .addComponent(jtfAngMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlfAngLibreMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAngLibreMicro3Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlfAngLibreMicro3AeroSufijo)
                        .addComponent(jlResMicro3Aero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosLibre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosLibre3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAngMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlAngMicro4AeroSufijo)
                        .addComponent(jtfAngMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlfAngLibreMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfAngLibreMicro4Aero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlfAngLibreMicro4AeroSufijo)
                        .addComponent(jlResMicro4Aero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPosLibre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPosLibre4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCalculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCalculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(409, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void cambioAsunto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioAsunto
    try {
        AsuntoRA asunto;
        
        limpiarCampos();

        Integer idAsunto = (Integer) ComboBoxObject.getClaveSelCombo(this.jcbAsunto);
        asunto = idAsunto != null ? AsuntoRA.getAsuntoPorId(idAsunto) : null;

        if (asunto != null) {
            AerogeneradorRA aero = asunto.getIdAero() != null ? AerogeneradorRA.getAeroPorId(asunto.getIdAero()) : null;
            this.jtfPosMicro1.setText(aero != null && aero.getHB() != null ? aero.getHB().toString() : null);
            
            NormaRA norma = asunto.getIdNorma() != null ? NormaRA.getNormaPorId(asunto.getIdNorma()) : null;
            this.jtfNorma.setText(norma != null ? norma.getNombre() : null);
            
            AsuntoPosicionRA asuntoPos = AsuntoPosicionRA.getAsuntoPosicionRA(idAsunto);
            if (asuntoPos != null) {
                PosicionRA posAero = asuntoPos.getIdPosAero() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosAero()) : null;
                this.jtfPosAero.setText(posAero != null ? posAero.toString() : null);
                
                PosicionRA posMicro1 = asuntoPos.getIdPosMicro1() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro1()) : null;
                this.jtfPosMicro1.setText(posMicro1 != null ? posMicro1.toString() : null);
                
                PosicionRA posMicro2 = asuntoPos.getIdPosMicro2() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro2()) : null;
                this.jtfPosMicro2.setText(posMicro2 != null ? posMicro2.toString() : null);
                
                PosicionRA posMicro3 = asuntoPos.getIdPosMicro3() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro3()) : null;
                this.jtfPosMicro3.setText(posMicro3 != null ? posMicro3.toString() : null);
                
                PosicionRA posMicro4 = asuntoPos.getIdPosMicro4() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro4()) : null;
                this.jtfPosMicro4.setText(posMicro4 != null ? posMicro4.toString() : null);

				Double hB = aero != null && aero.getHB() != null ? aero.getHB() : 0.0;
				Double longBuje = aero != null && aero.getLongBuje() != null ? aero.getLongBuje() : 0.0;
					
				PosicionRA posBuje = DatosRA2.getPosicionBuje(posAero, posMicro1, hB, longBuje);
				
				this.jtfPosBuje.setText(posBuje != null ? posBuje.toString() : null);
			}
            
            this.jtfRutaMallado.setEnabled(true);
            this.jbSelRuta.setEnabled(true);
            
            this.jbCalcular.setEnabled(true);
        }
    } catch (SQLException e) {
        MensajeApp.muestraError(this, e, "Fallo al consultar la base de datos");
    } catch (NoSuchFieldException e) {
        MensajeApp.muestraError(this, e, "Fallo añadiendo campo");
    }
}//GEN-LAST:event_cambioAsunto

private void calcularAngulos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularAngulos
    limpiarCalculos();
    
    if (Auxiliares.validaCampos(this)) {
        try {
            Double[][] mallado = Auxiliares.leeMalladoFichero(this.jtfRutaMallado.getText());

            Integer idAsunto = (Integer) ComboBoxObject.getClaveSelCombo(this.jcbAsunto);
            AsuntoPosicionRA asuntoPos = AsuntoPosicionRA.getAsuntoPosicionRA(idAsunto);

            PosicionRA posAero = asuntoPos.getIdPosAero() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosAero()) : null;
            PosicionRA posMicro1 = asuntoPos.getIdPosMicro1() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro1()) : null;
            PosicionRA posMicro2 = asuntoPos.getIdPosMicro2() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro2()) : null;
            PosicionRA posMicro3 = asuntoPos.getIdPosMicro3() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro3()) : null;
            PosicionRA posMicro4 = asuntoPos.getIdPosMicro4() != null ? PosicionRA.getPosicion(asuntoPos.getIdPosMicro4()) : null;

            LineString rectaMicroAero;
            Double angMicroAero, angMinLibre, angLibre;
            if (posAero != null) {
                PosicionRA posBuje = posAero;
				ArrayList<PosicionRA> posCorte = new ArrayList<PosicionRA>();
                
                if (posAero != null && posMicro1 != null) {
                    AsuntoRA asunto = AsuntoRA.getAsuntoPorId(idAsunto);
                    AerogeneradorRA aero = asunto.getIdAero() != null ? AerogeneradorRA.getAeroPorId(asunto.getIdAero()) : null;
					Double hB = aero != null && aero.getHB() != null ? aero.getHB() : 0.0;
                    Double longBuje = aero != null && aero.getLongBuje() != null ? aero.getLongBuje() : 0.0;
                    
                    posBuje = DatosRA2.getPosicionBuje(posAero, posMicro1, hB, longBuje);
                }
                
                if (posMicro1 != null) {
                     rectaMicroAero = Auxiliares.getRecta3D(posMicro1.getPosX(), posMicro1.getPosY(), posMicro1.getPosZ(), posBuje.getPosX(), posBuje.getPosY(), posBuje.getPosZ());
                     angMicroAero = Auxiliares.getAnguloRectaPlano(rectaMicroAero);
                     angMinLibre = Auxiliares.getAnguloMaxConMallado(rectaMicroAero, mallado, posCorte);

                     this.jtfAngMicro1Aero.setText(angMicroAero != null ? Auxiliares.getAnguloDecimal(angMicroAero).toString() : null);
                     this.jtfAngLibreMicro1Aero.setText(angMinLibre != null ? Auxiliares.getAnguloDecimal(angMinLibre).toString() : null);

					 this.jtfPosLibre1.setText(posCorte.get(0).toString());

                     if (angMicroAero != null && angMinLibre != null) {
                         angLibre = Auxiliares.getAnguloDecimal(angMicroAero - angMinLibre);

                         if (angLibre >= 25.0 && angLibre <= 40.0) {
                             this.jlResMicro1Aero.setText("OK");
                             this.jlResMicro1Aero.setBackground(Color.GREEN);
                         } else {
                             this.jlResMicro1Aero.setText("NO OK");
                             this.jlResMicro1Aero.setBackground(Color.RED);
                         }
                     }
                }

                if (posMicro2 != null) {
                     rectaMicroAero = Auxiliares.getRecta3D(posMicro2.getPosX(), posMicro2.getPosY(), posMicro2.getPosZ(), posBuje.getPosX(), posBuje.getPosY(), posBuje.getPosZ());
                     angMicroAero = Auxiliares.getAnguloRectaPlano(rectaMicroAero);
                     angMinLibre = Auxiliares.getAnguloMaxConMallado(rectaMicroAero, mallado, posCorte);

                     this.jtfAngMicro2Aero.setText(angMicroAero != null ? Auxiliares.getAnguloDecimal(angMicroAero).toString() : null);
                     this.jtfAngLibreMicro2Aero.setText(angMinLibre != null ? Auxiliares.getAnguloDecimal(angMinLibre).toString() : null);

					 this.jtfPosLibre2.setText(posCorte.get(0).toString());

                     if (angMicroAero != null && angMinLibre != null) {
                         angLibre = Auxiliares.getAnguloDecimal(angMicroAero - angMinLibre);
                     
                         if (angLibre >= 25.0 && angLibre <= 40.0) {
                             this.jlResMicro2Aero.setText("OK");
                             this.jlResMicro2Aero.setBackground(Color.GREEN);
                         } else {
                             this.jlResMicro2Aero.setText("NO OK");
                             this.jlResMicro2Aero.setBackground(Color.RED);
                         }
                     }
                }

                if (posMicro3 != null) {
                     rectaMicroAero = Auxiliares.getRecta3D(posMicro3.getPosX(), posMicro3.getPosY(), posMicro3.getPosZ(), posBuje.getPosX(), posBuje.getPosY(), posBuje.getPosZ());
                     angMicroAero = Auxiliares.getAnguloRectaPlano(rectaMicroAero);
                     angMinLibre = Auxiliares.getAnguloMaxConMallado(rectaMicroAero, mallado, posCorte);

                     this.jtfAngMicro3Aero.setText(angMicroAero != null ? Auxiliares.getAnguloDecimal(angMicroAero).toString() : null);
                     this.jtfAngLibreMicro3Aero.setText(angMinLibre != null ? Auxiliares.getAnguloDecimal(angMinLibre).toString() : null);

					 this.jtfPosLibre3.setText(posCorte.get(0).toString());

                     if (angMicroAero != null && angMinLibre != null) {
                         angLibre = Auxiliares.getAnguloDecimal(angMicroAero - angMinLibre);
                     
                         if (angLibre >= 25.0 && angLibre <= 40.0) {
                             this.jlResMicro3Aero.setText("OK");
                             this.jlResMicro3Aero.setBackground(Color.GREEN);
                         } else {
                             this.jlResMicro3Aero.setText("NO OK");
                             this.jlResMicro3Aero.setBackground(Color.RED);
                         }
                     }
                }

                if (posMicro4 != null) {
                     rectaMicroAero = Auxiliares.getRecta3D(posMicro4.getPosX(), posMicro4.getPosY(), posMicro4.getPosZ(), posBuje.getPosX(), posBuje.getPosY(), posBuje.getPosZ());
                     angMicroAero = Auxiliares.getAnguloRectaPlano(rectaMicroAero);
                     angMinLibre = Auxiliares.getAnguloMaxConMallado(rectaMicroAero, mallado, posCorte);

                     this.jtfAngMicro4Aero.setText(angMicroAero != null ? Auxiliares.getAnguloDecimal(angMicroAero).toString() : null);
                     this.jtfAngLibreMicro4Aero.setText(angMinLibre != null ? Auxiliares.getAnguloDecimal(angMinLibre).toString() : null);

					 this.jtfPosLibre4.setText(posCorte.get(0).toString());

                     if (angMicroAero != null && angMinLibre != null) {
                         angLibre = Auxiliares.getAnguloDecimal(angMicroAero - angMinLibre);
                     
                         if (angLibre >= 25.0 && angLibre <= 40.0) {
                             this.jlResMicro4Aero.setText("OK");
                             this.jlResMicro4Aero.setBackground(Color.GREEN);
                         } else {
                             this.jlResMicro4Aero.setText("NO OK");
                             this.jlResMicro4Aero.setBackground(Color.RED);
                         }
                     }
                }
            }
        } catch (SQLException e) {
            MensajeApp.muestraError(this, e, "Fallo al consultar la base de datos");
        } catch (NoSuchFieldException e) {
            MensajeApp.muestraError(this, e, "Fallo añadiendo campo");
        } catch (IOException e) {
            MensajeApp.muestraError(this, e, "Fallo accediendo a fichero");
        }
    }

}//GEN-LAST:event_calcularAngulos

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        //Rellenamos combo de asuntos con los relacionados con el parque
        Auxiliares.cargaAsuntos(this.jcbAsunto);
        
        //Añadimos los verificadores de los campos de entrada
        this.jtfRutaMallado.setInputVerifier(new IVExtendido(this, IVExtendido.TIPO_STRING, false, false));
    } catch (SQLException e) {
        MensajeApp.muestraError(this, e, "Fallo al consultar la base de datos");
        this.dispose();
    } catch (NoSuchFieldException e) {
        MensajeApp.muestraError(this, e, "Fallo añadiendo campo");
        this.dispose();
    }
}//GEN-LAST:event_formWindowOpened

private void seleccionarRuta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarRuta
    JFileChooser fc = new JFileChooser(Auxiliares.dameRutaDefecto(this)); 
    fc.setMultiSelectionEnabled(false);
        
    int seleccion = fc.showOpenDialog(this);              

    if (seleccion == JFileChooser.APPROVE_OPTION) {
        this.jtfRutaMallado.setText(fc.getSelectedFile().getPath());
        this.jtfRutaMallado.setCaretPosition(0);
    }
}//GEN-LAST:event_seleccionarRuta

private void limpiarCampos() {
    //Campos de cabecera
    this.jtfNorma.setText(null);
    this.jtfPosAero.setText(null);
    this.jtfPosBuje.setText(null);
    this.jtfPosMicro1.setText(null);
    this.jtfPosMicro2.setText(null);
    this.jtfPosMicro4.setText(null);
    this.jtfPosMicro3.setText(null);
    
    this.jtfRutaMallado.setText(null);
    this.jtfRutaMallado.setEnabled(false);
    this.jbSelRuta.setEnabled(false);

    this.jbCalcular.setEnabled(false);
    
    limpiarCalculos();
}

private void limpiarCalculos() {
    this.jtfAngMicro1Aero.setText(null);
    this.jtfAngMicro2Aero.setText(null);
    this.jtfAngMicro3Aero.setText(null);
    this.jtfAngMicro4Aero.setText(null);
    this.jtfAngMicro1Aero.setBackground(new Color(236,233,216));
    this.jtfAngMicro2Aero.setBackground(new Color(236,233,216));
    this.jtfAngMicro3Aero.setBackground(new Color(236,233,216));
    this.jtfAngMicro4Aero.setBackground(new Color(236,233,216));
    
    this.jtfAngLibreMicro1Aero.setText(null);
    this.jtfAngLibreMicro2Aero.setText(null);
    this.jtfAngLibreMicro3Aero.setText(null);
    this.jtfAngLibreMicro4Aero.setText(null);
    
    this.jlResMicro1Aero.setText(null);
    this.jlResMicro2Aero.setText(null);
    this.jlResMicro3Aero.setText(null);
    this.jlResMicro4Aero.setText(null);

    this.jtfPosLibre1.setText(null);
    this.jtfPosLibre2.setText(null);
    this.jtfPosLibre3.setText(null);
    this.jtfPosLibre4.setText(null);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbSelRuta;
    public javax.swing.JComboBox jcbAsunto;
    private javax.swing.JLabel jlAngMicro1Aero;
    private javax.swing.JLabel jlAngMicro1AeroSufijo;
    private javax.swing.JLabel jlAngMicro2Aero;
    private javax.swing.JLabel jlAngMicro2AeroSufijo;
    private javax.swing.JLabel jlAngMicro3Aero;
    private javax.swing.JLabel jlAngMicro3AeroSufijo;
    private javax.swing.JLabel jlAngMicro4Aero;
    private javax.swing.JLabel jlAngMicro4AeroSufijo;
    private javax.swing.JLabel jlAsunto;
    private javax.swing.JLabel jlNorma;
    private javax.swing.JLabel jlPosAero;
    private javax.swing.JLabel jlPosBuje;
    private javax.swing.JLabel jlPosLibre1;
    private javax.swing.JLabel jlPosLibre2;
    private javax.swing.JLabel jlPosLibre3;
    private javax.swing.JLabel jlPosLibre4;
    private javax.swing.JLabel jlPosMicro1;
    private javax.swing.JLabel jlPosMicro2;
    private javax.swing.JLabel jlPosMicro3;
    private javax.swing.JLabel jlPosMicro4;
    private javax.swing.JLabel jlResMicro1Aero;
    private javax.swing.JLabel jlResMicro2Aero;
    private javax.swing.JLabel jlResMicro3Aero;
    private javax.swing.JLabel jlResMicro4Aero;
    private javax.swing.JLabel jlRutaMallado;
    private javax.swing.JLabel jlfAngLibreMicro1Aero;
    private javax.swing.JLabel jlfAngLibreMicro1AeroSufijo;
    private javax.swing.JLabel jlfAngLibreMicro2Aero;
    private javax.swing.JLabel jlfAngLibreMicro2AeroSufijo;
    private javax.swing.JLabel jlfAngLibreMicro3Aero;
    private javax.swing.JLabel jlfAngLibreMicro3AeroSufijo;
    private javax.swing.JLabel jlfAngLibreMicro4Aero;
    private javax.swing.JLabel jlfAngLibreMicro4AeroSufijo;
    private javax.swing.JPanel jpCalculos;
    private javax.swing.JPanel jpClave;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JTextField jtfAngLibreMicro1Aero;
    private javax.swing.JTextField jtfAngLibreMicro2Aero;
    private javax.swing.JTextField jtfAngLibreMicro3Aero;
    private javax.swing.JTextField jtfAngLibreMicro4Aero;
    private javax.swing.JTextField jtfAngMicro1Aero;
    private javax.swing.JTextField jtfAngMicro2Aero;
    private javax.swing.JTextField jtfAngMicro3Aero;
    private javax.swing.JTextField jtfAngMicro4Aero;
    private javax.swing.JTextField jtfNorma;
    public javax.swing.JTextField jtfPosAero;
    public javax.swing.JTextField jtfPosBuje;
    public javax.swing.JTextField jtfPosLibre1;
    public javax.swing.JTextField jtfPosLibre2;
    public javax.swing.JTextField jtfPosLibre3;
    public javax.swing.JTextField jtfPosLibre4;
    public javax.swing.JTextField jtfPosMicro1;
    public javax.swing.JTextField jtfPosMicro2;
    public javax.swing.JTextField jtfPosMicro3;
    public javax.swing.JTextField jtfPosMicro4;
    public javax.swing.JTextField jtfRutaMallado;
    // End of variables declaration//GEN-END:variables

}
